### ISSUE TITLE
Merge `am_list` back into `am`

### ISSUE THREAD

**Issue by gagbo** [autometrics-dev/am#114]
Now that [`am_list`](https://github.com/autometrics-dev/am_list) (both the binary and the library) is stable, it's probably ready to be included in `am` entirely. There are 2 main things to take care of when integrating this:

- as the library is used in other projects (including the WIP github app) the library part of `am` must either:
  + be fully available on crates.io, or
  + have `am_list` as a workspace member that can be published

In any case, it's probably going to have an impact on the release cycle for `am`, as adding/fixing support for specific languages must trigger a new version release as soon as possible for the dependent projects.

- What should be the name of the subcommand for listing the names of the functions in the project ?

I think all the rest can be handled without too much issue, I can do that integration once those points are solved.

**Comment by mellowagain** [comment]
i think there is nothing stopping us from publishing the `am` library on crates.io, no? it's already setup this way as we have two crates in this repo actually, `am` (the cli tool) and `autometrics-am` (the library).

imo adjusting the release schedule also doesnt seem like a problem

for the subcommand, maybe something like `am functions`?

**Comment by gagbo** [comment]
I also need to remember to change the [download location](https://github.com/autometrics-dev/diff-metrics/blob/main/src/am_list.ts#L20-L23) in the github action. I'll try to track the issue there as well

**Comment by gagbo** [comment]
Seems like it's going to be the plan:

- `am_list` won't be published on crates-io anymore: for the time being there are no dependents on `am_list` that _also_ want to be on crates-io. This means all dependents on `am_list` can just use a git-dependency in their Cargo.toml
- `am_list` will just be included as a subdirectory of the library: for the time being, `am` is not a workspace, and changing that adds a lot of extra work that's not really necessary today. To balance the risk of having a huge dependency tree when someone just wants the `am_list` library part, the library part of `am` will have a lot of features about each submodule (all active by default, for the binary). Then dependents can pick each part of `am` they want using `no-default-features = true`
- The name of the subcommand is TBD, but also not important for now. It's important though to remember we want essentially 2 things added to `am`:
  + listing all the functions in a (local) project
  + querying the name/module/instrumentation status of anything under the given location (`(file_name, line, column)`)
