### ISSUE TITLE
Allow user to specify the name of the job

### ISSUE THREAD

**Issue by hatchan** [autometrics-dev/am#49]
Each target can have a name. This will be exposed as the `job` label in the metrics. It would be useful for the user to specify these names.

Currently we just have `app_{}` where the parenthesis will contain a incrementing number (to avoid collisions).

With a config file we can simply add another property, something like name. For the terminal approach, we might want to include a prefix or postfix. So something like `api|:3000`. The first part would be the name of the job, in this case `api`, and the part after the `|` will just be parsed as it currently is.

**Comment by hatchan** [comment]
I was thinking that now that we have support for a toml file it might make sense to just keep it there and not make the parsing of the cli arguments _too_ complicated to use. Any thoughts on this @mies @mellowagain

**Comment by mies** [comment]
I'd be in favor of reducing the complexity and number of arguments for the cli 🥳

**Comment by hatchan** [comment]
> where is job name even displayed? its not displayed in dora at all, right? only in prom/grafana, in which case yea config should be fine

It is used in Prometheus. This jobname would be added to the metrics as a label that would be produced by this endpoint.
