### ISSUE TITLE
Show explorer, prometheus, pushgateway, etc details once everything is started

### ISSUE THREAD

**Issue by hatchan** [autometrics-dev/am#53]
We should only display the details once the download and unpack is complete for both prometheus and pushgateway.

This is not an issue when the users already has the applications cached. But it does give a poor experience for a first time user.

**Comment by hatchan** [comment]
This could actually be a more persistent interface with some keyboard shortcuts. @keturiosakys mentioned VITE, which allows you to quickly open a browser, while it shows all the other relevant information about the server. There are some other hotkeys as well. Tilt does a similar thing.

For `am` we could show all the relevant endpoints once it starts and then allow space to be used to open the explorer page. Additionally you can interact with the running `am` server with other hot keys (such as restart prometheus, or change the scrape interval). We do need to figure out how to combine this with our current logging implementation.

**Comment by keturiosakys** [comment]
Here are a couple of example screenshots of how Vite and its cousin Vitest run in the shell when active:

<img width="448" alt="CleanShot 2023-06-28 at 14 39 14@2x" src="https://github.com/autometrics-dev/am/assets/17225208/0f818dec-aeec-48e1-be6e-21b82d270e64">
<img width="448" alt="CleanShot 2023-06-28 at 14 39 14@2x" src="https://github.com/autometrics-dev/am/assets/17225208/f0b24d9c-8ce2-4bcd-81a3-37cec128f325">

**Comment by hatchan** [comment]
A example of how tilt does it (screenshot by @stephlow, thanks). 
![Screenshot 2023-06-28 at 14 44 02](https://github.com/autometrics-dev/am/assets/202981/0ad6cccf-60b4-4fe8-81a1-75c2254c715c)
