### ISSUE TITLE
Add `explore` command

### ISSUE THREAD

**Issue by hatchan** [autometrics-dev/am#74]
This command would be used by a user to open the explorer in their browser. It should also display the URL and allow for an option to not open the browser.

By default the URL that is opened should point to the local explorer giving its defaults. 

The first argument to `explore` can be a different Prometheus endpoint. This will still use the same explorer instance but it will pass this Prometheus endpoint to explorer to use. Example: `am explore https://prometheus.example.com`.

We should also be able to use a different explorer endpoint, so this should be another argument. Example: `am explore --explorer-endpoint https://explorer.autometrics.dev`.

The defaults for the Prometheus endpoint and explorer endpoint should also come from a am configuration file for the user.

# Open questions

Currently `am start` set the Prometheus URL as field in the html. In the scenario where we use a different explorer endpoint we have no control over the html and so we need a different way of passing the Prometheus URL to explorer. This would probably be a query-string parameter.

**Comment by brettimus** [comment]
as a heads up, benno and i discussed in slack, and the currently live/deployed explorer will support doing this via a `?prometheusUrl` query parameter
