### ISSUE TITLE
support `am init` command

### ISSUE THREAD

**Issue by mies** [autometrics-dev/am#97]
This command would generate a `am.toml` file with some sensible defaults and ideally show a wizard that will ask the relevant questions;

* what are the metric endpoints of your application
* do you want push gateway

etc

**Comment by hatchan** [comment]
We can extend this in the future when we have multiple purposes for the am tool, such as self hosting or agent mode.

The first question could be what is the intended use case and based on the answer we can show certain questions and write into different files.
